# Generated by Django 3.2.3 on 2021-07-20 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0002_auto_20210519_1621"),
    ]

    operations = [
        migrations.CreateModel(
            name="RazstaviVieta",
            fields=[
                (
                    "problem_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="problems.problem",
                    ),
                ),
                ("maksimalna_vrednost", models.PositiveSmallIntegerField()),
                ("vodilni_koeficient", models.BooleanField()),
            ],
            bases=("problems.problem",),
        ),
    ]
