# Generated by Django 3.2.3 on 2021-07-20 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0003_razstavivieta"),
    ]

    operations = [
        migrations.CreateModel(
            name="RazstaviRazliko",
            fields=[
                (
                    "problem_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="problems.problem",
                    ),
                ),
                ("najmanjsa_potenca", models.PositiveSmallIntegerField()),
                ("najvecja_potenca", models.PositiveSmallIntegerField()),
                ("linearna_kombinacija", models.BooleanField()),
            ],
            bases=("problems.problem",),
        ),
    ]
