# Generated by Django 3.2.3 on 2021-07-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0004_razstavirazliko"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="iskanjenicelpolinoma",
            options={"verbose_name": "iskanje ničel polinoma"},
        ),
        migrations.AlterModelOptions(
            name="krajsanjeulomkov",
            options={"verbose_name": "krajšanje ulomkov"},
        ),
        migrations.AlterModelOptions(
            name="prostobesedilo",
            options={"verbose_name": "prosto besedilo"},
        ),
        migrations.AlterModelOptions(
            name="razstavirazliko",
            options={"verbose_name": "razstavi razliko"},
        ),
        migrations.AlterModelOptions(
            name="razstavivieta",
            options={"verbose_name": "razstavi Vieta"},
        ),
        migrations.AlterField(
            model_name="iskanjenicelpolinoma",
            name="stevilo_nicel",
            field=models.PositiveSmallIntegerField(
                help_text="Največje število ničel polinoma (vedno bo vsaj 1).",
                verbose_name="število ničel",
            ),
        ),
        migrations.AlterField(
            model_name="iskanjenicelpolinoma",
            name="velikost_nicle",
            field=models.PositiveSmallIntegerField(
                help_text="Največja velikost ničle glede na absolutno vrednost.",
                verbose_name="velikost ničle",
            ),
        ),
        migrations.AlterField(
            model_name="krajsanjeulomkov",
            name="najvecji_faktor",
            field=models.PositiveSmallIntegerField(
                help_text="Največji faktor med neokrajšanim in okrajšanim ulomkom.",
                verbose_name="največji faktor",
            ),
        ),
        migrations.AlterField(
            model_name="krajsanjeulomkov",
            name="najvecji_imenovalec",
            field=models.PositiveSmallIntegerField(
                help_text="Največji imenovalec, ki se bo pojavljal v okrajšanem ulomku.",
                verbose_name="največji imenovalec",
            ),
        ),
        migrations.AlterField(
            model_name="krajsanjeulomkov",
            name="najvecji_stevec",
            field=models.PositiveSmallIntegerField(
                help_text="Največji števec, ki se bo pojavljal v okrajšanem ulomku.",
                verbose_name="največji števec",
            ),
        ),
        migrations.AlterField(
            model_name="prostobesedilo",
            name="odgovor",
            field=models.TextField(
                help_text="Poljubno besedilo odgovora.", verbose_name="odgovor"
            ),
        ),
        migrations.AlterField(
            model_name="prostobesedilo",
            name="vprasanje",
            field=models.TextField(
                help_text="Poljubno besedilo vprašanja.", verbose_name="vprašanje"
            ),
        ),
        migrations.AlterField(
            model_name="razstavirazliko",
            name="linearna_kombinacija",
            field=models.BooleanField(
                help_text="Ali naj naloga vsebuje linearno kombinacijo dveh neznank ali enostaven dvočlenik?",
                verbose_name="linearna kombinacija",
            ),
        ),
        migrations.AlterField(
            model_name="razstavirazliko",
            name="najmanjsa_potenca",
            field=models.PositiveSmallIntegerField(
                help_text="Najmanjša možna potenca za razstavljanje.",
                verbose_name="najmanjša potenca",
            ),
        ),
        migrations.AlterField(
            model_name="razstavirazliko",
            name="najvecja_potenca",
            field=models.PositiveSmallIntegerField(
                help_text="Največja možna potenca za razstavljanje.",
                verbose_name="največja potenca",
            ),
        ),
        migrations.AlterField(
            model_name="razstavivieta",
            name="maksimalna_vrednost",
            field=models.PositiveSmallIntegerField(
                help_text="Največja možna vrednost razstavljenega člena glede na absolutno vrednost",
                verbose_name="maksimalna vrednost",
            ),
        ),
        migrations.AlterField(
            model_name="razstavivieta",
            name="vodilni_koeficient",
            field=models.BooleanField(
                help_text="Ali naj bo vodilni koeficient različen od 1?",
                verbose_name="vodilni koeficient",
            ),
        ),
    ]
