# Generated by Django 3.2.3 on 2021-08-12 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "problems",
            "0006_elementimnozice_izpeljanemnozice_operacijemnozic_potencnamnozica",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="PotencaDvoclenika",
            fields=[
                (
                    "problem_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="problems.problem",
                    ),
                ),
                (
                    "najmanjsa_potenca",
                    models.PositiveSmallIntegerField(
                        help_text="Najmanjša možna potenca dvočlenika.",
                        verbose_name="najmanjša potenca",
                    ),
                ),
                (
                    "najvecja_potenca",
                    models.PositiveSmallIntegerField(
                        help_text="Največja možna potenca dvočlenika.",
                        verbose_name="največja potenca",
                    ),
                ),
                (
                    "linearna_kombinacija",
                    models.BooleanField(
                        help_text="Ali naj naloga vsebuje linearno kombinacijo dveh neznank ali enostaven dvočlenik?",
                        verbose_name="linearna kombinacija",
                    ),
                ),
            ],
            options={
                "verbose_name": "potenciranje dvočlenika",
            },
            bases=("problems.problem",),
        ),
        migrations.CreateModel(
            name="PotencaTroclenika",
            fields=[
                (
                    "problem_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="problems.problem",
                    ),
                ),
                (
                    "najmanjsa_potenca",
                    models.PositiveSmallIntegerField(
                        help_text="Najmanjša možna potenca tročlenika.",
                        verbose_name="najmanjša potenca",
                    ),
                ),
                (
                    "najvecja_potenca",
                    models.PositiveSmallIntegerField(
                        help_text="Največja možna potenca dvočlenika.",
                        verbose_name="največja potenca",
                    ),
                ),
                (
                    "linearna_kombinacija",
                    models.BooleanField(
                        help_text="Ali naj naloga vsebuje linearno kombinacijo treh neznank ali enostaven tročlenik?",
                        verbose_name="linearna kombinacija",
                    ),
                ),
            ],
            options={
                "verbose_name": "potenciranje tročlenika",
            },
            bases=("problems.problem",),
        ),
        migrations.CreateModel(
            name="PotencaVecclenika",
            fields=[
                (
                    "problem_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="problems.problem",
                    ),
                ),
                (
                    "najmanjsa_potenca",
                    models.PositiveSmallIntegerField(
                        help_text="Najmanjša možna potenca veččlenika.",
                        verbose_name="najmanjša potenca",
                    ),
                ),
                (
                    "najvecja_potenca",
                    models.PositiveSmallIntegerField(
                        help_text="Največja možna potenca veččlenika.",
                        verbose_name="največja potenca",
                    ),
                ),
                (
                    "najmanj_clenov",
                    models.PositiveSmallIntegerField(
                        help_text="Najmanjše možno število členov v veččleniku.",
                        verbose_name="najmanjša potenca",
                    ),
                ),
                (
                    "najvec_clenov",
                    models.PositiveSmallIntegerField(
                        help_text="Največje možno število členov v veččleniku.",
                        verbose_name="največja potenca",
                    ),
                ),
                (
                    "linearna_kombinacija",
                    models.BooleanField(
                        help_text="Ali naj naloga vsebuje linearno kombinacijo neznank ali enostaven veččlenik?",
                        verbose_name="linearna kombinacija",
                    ),
                ),
            ],
            options={
                "verbose_name": "potenciranje veččlenika",
            },
            bases=("problems.problem",),
        ),
    ]
