# Generated by Django 3.2.3 on 2021-08-28 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0007_potencadvoclenika_potencatroclenika_potencavecclenika"),
    ]

    operations = [
        migrations.CreateModel(
            name="KompleksnaEnacba",
            fields=[
                (
                    "problem_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="problems.problem",
                    ),
                ),
                (
                    "konjugirana_vrednost",
                    models.BooleanField(
                        choices=[(True, "Da"), (False, "Ne")],
                        help_text="Ali naj naloga vsebuje konjugirano vrednost?",
                        verbose_name="konjugirana vrednost",
                    ),
                ),
            ],
            options={
                "verbose_name": "enačbe s kompleksnimi števili",
            },
            bases=("problems.problem",),
        ),
        migrations.CreateModel(
            name="KompleksniUlomek",
            fields=[
                (
                    "problem_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="problems.problem",
                    ),
                ),
            ],
            options={
                "verbose_name": "seštevanje in racionalizacija kompleksnih ulomkov",
            },
            bases=("problems.problem",),
        ),
        migrations.CreateModel(
            name="MnozenjeKompleksnih",
            fields=[
                (
                    "problem_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="problems.problem",
                    ),
                ),
            ],
            options={
                "verbose_name": "množenje kompleksnih števil",
            },
            bases=("problems.problem",),
        ),
        migrations.CreateModel(
            name="NarisiKompleksna",
            fields=[
                (
                    "problem_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="problems.problem",
                    ),
                ),
            ],
            options={
                "verbose_name": "risanje kompleksnih števil",
            },
            bases=("problems.problem",),
        ),
        migrations.CreateModel(
            name="RacunanjeKompleksno",
            fields=[
                (
                    "problem_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="problems.problem",
                    ),
                ),
            ],
            options={
                "verbose_name": "računanje z kompleksno enoto",
            },
            bases=("problems.problem",),
        ),
        migrations.CreateModel(
            name="VsotaKompleksnih",
            fields=[
                (
                    "problem_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="problems.problem",
                    ),
                ),
            ],
            options={
                "verbose_name": "vsota in razlika kompleksnih števil",
            },
            bases=("problems.problem",),
        ),
        migrations.AlterField(
            model_name="potencavecclenika",
            name="najmanj_clenov",
            field=models.PositiveSmallIntegerField(
                help_text="Najmanjše možno število členov v veččleniku.",
                verbose_name="najmanj členov",
            ),
        ),
        migrations.AlterField(
            model_name="potencavecclenika",
            name="najvec_clenov",
            field=models.PositiveSmallIntegerField(
                help_text="Največje možno število členov v veččleniku.",
                verbose_name="največ členov",
            ),
        ),
    ]
