# Generated by Django 3.2.6 on 2021-09-16 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0009_auto_20210909_2125"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliteljveckratnik",
            name="maksimalna_vrednost",
            field=models.PositiveSmallIntegerField(
                default=500,
                help_text="Največja možna vrednost katerega izmed števil",
                verbose_name="maksimalna vrednost",
            ),
        ),
        migrations.AlterField(
            model_name="deliteljveckratnik",
            name="maksimalni_prafaktor",
            field=models.PositiveSmallIntegerField(
                default=11,
                help_text="Zgornja meja za prafaktorje števil",
                verbose_name="maksimalni prafaktor",
            ),
        ),
        migrations.AlterField(
            model_name="deliteljveckratnik",
            name="minimalna_vrednost",
            field=models.PositiveSmallIntegerField(
                default=20,
                help_text="Najmanjša možna vrednost katerega izmed števil",
                verbose_name="minimalna vrednost",
            ),
        ),
        migrations.AlterField(
            model_name="elementimnozice",
            name="linearna_kombinacija",
            field=models.BooleanField(
                choices=[(True, "Da"), (False, "Ne")],
                default=True,
                help_text="Ali naj naloga vsebuje linearno kombinacijo?",
                verbose_name="linearna kombinacija",
            ),
        ),
        migrations.AlterField(
            model_name="iskanjenicelpolinoma",
            name="stevilo_nicel",
            field=models.PositiveSmallIntegerField(
                default=3,
                help_text="Največje število ničel polinoma (vedno bo vsaj 1).",
                verbose_name="število ničel",
            ),
        ),
        migrations.AlterField(
            model_name="iskanjenicelpolinoma",
            name="velikost_nicle",
            field=models.PositiveSmallIntegerField(
                default=9,
                help_text="Največja velikost ničle glede na absolutno vrednost.",
                verbose_name="velikost ničle",
            ),
        ),
        migrations.AlterField(
            model_name="kompleksnaenacba",
            name="konjugirana_vrednost",
            field=models.BooleanField(
                choices=[(True, "Da"), (False, "Ne")],
                default=True,
                help_text="Ali naj naloga vsebuje konjugirano vrednost?",
                verbose_name="konjugirana vrednost",
            ),
        ),
        migrations.AlterField(
            model_name="krajsanjeulomkov",
            name="najvecji_faktor",
            field=models.PositiveSmallIntegerField(
                default=20,
                help_text="Največji faktor med neokrajšanim in okrajšanim ulomkom.",
                verbose_name="največji faktor",
            ),
        ),
        migrations.AlterField(
            model_name="krajsanjeulomkov",
            name="najvecji_imenovalec",
            field=models.PositiveSmallIntegerField(
                default=20,
                help_text="Največji imenovalec, ki se bo pojavljal v okrajšanem ulomku.",
                verbose_name="največji imenovalec",
            ),
        ),
        migrations.AlterField(
            model_name="krajsanjeulomkov",
            name="najvecji_stevec",
            field=models.PositiveSmallIntegerField(
                default=20,
                help_text="Največji števec, ki se bo pojavljal v okrajšanem ulomku.",
                verbose_name="največji števec",
            ),
        ),
        migrations.AlterField(
            model_name="potencadvoclenika",
            name="linearna_kombinacija",
            field=models.BooleanField(
                default=True,
                help_text="Ali naj naloga vsebuje linearno kombinacijo dveh neznank ali enostaven dvočlenik?",
                verbose_name="linearna kombinacija",
            ),
        ),
        migrations.AlterField(
            model_name="potencadvoclenika",
            name="najmanjsa_potenca",
            field=models.PositiveSmallIntegerField(
                default=2,
                help_text="Najmanjša možna potenca dvočlenika.",
                verbose_name="najmanjša potenca",
            ),
        ),
        migrations.AlterField(
            model_name="potencadvoclenika",
            name="najvecja_potenca",
            field=models.PositiveSmallIntegerField(
                default=4,
                help_text="Največja možna potenca dvočlenika.",
                verbose_name="največja potenca",
            ),
        ),
        migrations.AlterField(
            model_name="potencatroclenika",
            name="linearna_kombinacija",
            field=models.BooleanField(
                default=True,
                help_text="Ali naj naloga vsebuje linearno kombinacijo treh neznank ali enostaven tročlenik?",
                verbose_name="linearna kombinacija",
            ),
        ),
        migrations.AlterField(
            model_name="potencatroclenika",
            name="najmanjsa_potenca",
            field=models.PositiveSmallIntegerField(
                default=2,
                help_text="Najmanjša možna potenca tročlenika.",
                verbose_name="najmanjša potenca",
            ),
        ),
        migrations.AlterField(
            model_name="potencatroclenika",
            name="najvecja_potenca",
            field=models.PositiveSmallIntegerField(
                default=4,
                help_text="Največja možna potenca dvočlenika.",
                verbose_name="največja potenca",
            ),
        ),
        migrations.AlterField(
            model_name="potencavecclenika",
            name="linearna_kombinacija",
            field=models.BooleanField(
                default=True,
                help_text="Ali naj naloga vsebuje linearno kombinacijo neznank ali enostaven veččlenik?",
                verbose_name="linearna kombinacija",
            ),
        ),
        migrations.AlterField(
            model_name="potencavecclenika",
            name="najmanj_clenov",
            field=models.PositiveSmallIntegerField(
                default=2,
                help_text="Najmanjše možno število členov v veččleniku.",
                verbose_name="najmanj členov",
            ),
        ),
        migrations.AlterField(
            model_name="potencavecclenika",
            name="najmanjsa_potenca",
            field=models.PositiveSmallIntegerField(
                default=2,
                help_text="Najmanjša možna potenca veččlenika.",
                verbose_name="najmanjša potenca",
            ),
        ),
        migrations.AlterField(
            model_name="potencavecclenika",
            name="najvec_clenov",
            field=models.PositiveSmallIntegerField(
                default=4,
                help_text="Največje možno število členov v veččleniku.",
                verbose_name="največ členov",
            ),
        ),
        migrations.AlterField(
            model_name="potencavecclenika",
            name="najvecja_potenca",
            field=models.PositiveSmallIntegerField(
                default=4,
                help_text="Največja možna potenca veččlenika.",
                verbose_name="največja potenca",
            ),
        ),
        migrations.AlterField(
            model_name="prostobesedilo",
            name="odgovor",
            field=models.TextField(
                default="",
                help_text="Poljubno besedilo odgovora.",
                verbose_name="odgovor",
            ),
        ),
        migrations.AlterField(
            model_name="prostobesedilo",
            name="vprasanje",
            field=models.TextField(
                default="",
                help_text="Poljubno besedilo vprašanja.",
                verbose_name="vprašanje",
            ),
        ),
        migrations.AlterField(
            model_name="razstavirazliko",
            name="linearna_kombinacija",
            field=models.BooleanField(
                default=True,
                help_text="Ali naj naloga vsebuje linearno kombinacijo dveh neznank ali enostaven dvočlenik?",
                verbose_name="linearna kombinacija",
            ),
        ),
        migrations.AlterField(
            model_name="razstavirazliko",
            name="najmanjsa_potenca",
            field=models.PositiveSmallIntegerField(
                default=2,
                help_text="Najmanjša možna potenca za razstavljanje.",
                verbose_name="najmanjša potenca",
            ),
        ),
        migrations.AlterField(
            model_name="razstavirazliko",
            name="najvecja_potenca",
            field=models.PositiveSmallIntegerField(
                default=4,
                help_text="Največja možna potenca za razstavljanje.",
                verbose_name="največja potenca",
            ),
        ),
        migrations.AlterField(
            model_name="razstavivieta",
            name="maksimalna_vrednost",
            field=models.PositiveSmallIntegerField(
                default=15,
                help_text="Največja možna vrednost razstavljenega člena glede na absolutno vrednost",
                verbose_name="maksimalna vrednost",
            ),
        ),
        migrations.AlterField(
            model_name="razstavivieta",
            name="vodilni_koeficient",
            field=models.BooleanField(
                default=True,
                help_text="Ali naj bo vodilni koeficient različen od 1?",
                verbose_name="vodilni koeficient",
            ),
        ),
    ]
