# Generated by Django 3.2.6 on 2021-09-21 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0010_auto_20210916_1043"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problemtext",
            name="answer",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="problemtext",
            name="question",
            field=models.TextField(),
        ),
    ]
