# Generated by Django 3.2.6 on 2021-09-23 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0011_auto_20210921_0902"),
    ]

    operations = [
        migrations.RenameField(
            model_name="problemtext",
            old_name="question",
            new_name="instruction",
        ),
        migrations.RenameField(
            model_name="problemtext",
            old_name="answer",
            new_name="solution",
        ),
        migrations.RenameField(
            model_name="prostobesedilo",
            old_name="odgovor",
            new_name="navodilo",
        ),
        migrations.RenameField(
            model_name="prostobesedilo",
            old_name="vprasanje",
            new_name="resitev",
        ),
    ]
