# Generated by Django 3.2.6 on 2021-09-24 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0013_auto_20210923_2006"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="deliteljveckratnik",
            options={
                "verbose_name": "Naravna števila / iskanje največjega skupnega delitelja in najmanjšega skupnega večkratnika"
            },
        ),
        migrations.AlterModelOptions(
            name="elementimnozice",
            options={"verbose_name": "Množice / elementi iz predpisa"},
        ),
        migrations.AlterModelOptions(
            name="evklidovalgoritem",
            options={"verbose_name": "Naravna števila / Evklidov algoritem"},
        ),
        migrations.AlterModelOptions(
            name="iskanjenicelpolinoma",
            options={"verbose_name": "??? / iskanje ničel polinoma"},
        ),
        migrations.AlterModelOptions(
            name="izpeljanemnozice",
            options={"verbose_name": "Množice / operacije na izpeljanih množicah"},
        ),
        migrations.AlterModelOptions(
            name="kompleksnaenacba",
            options={
                "verbose_name": "Kompleksna števila / reševanje enačb s kompleksnimi števili"
            },
        ),
        migrations.AlterModelOptions(
            name="kompleksniulomek",
            options={
                "verbose_name": "Kompleksna števila / seštevanje in racionalizacija ulomkov"
            },
        ),
        migrations.AlterModelOptions(
            name="krajsanjeulomkov",
            options={"verbose_name": "??? / krajšanje ulomkov"},
        ),
        migrations.AlterModelOptions(
            name="mnozenjekompleksnih",
            options={"verbose_name": "Kompleksna števila / množenje"},
        ),
        migrations.AlterModelOptions(
            name="narisikompleksna",
            options={"verbose_name": "??? / risanje v ravnino"},
        ),
        migrations.AlterModelOptions(
            name="operacijemnozic",
            options={"verbose_name": "Množice / operacije z množicami"},
        ),
        migrations.AlterModelOptions(
            name="potencadvoclenika",
            options={"verbose_name": "Veččleniki / potenciranje dvočlenika"},
        ),
        migrations.AlterModelOptions(
            name="potencatroclenika",
            options={"verbose_name": "Veččleniki / potenciranje tročlenika"},
        ),
        migrations.AlterModelOptions(
            name="potencavecclenika",
            options={"verbose_name": "Veččleniki / potenciranje veččlenika"},
        ),
        migrations.AlterModelOptions(
            name="potencnamnozica",
            options={"verbose_name": "Množice / potenčna množica"},
        ),
        migrations.AlterModelOptions(
            name="prostobesedilo",
            options={"verbose_name": "Razno / prosto besedilo"},
        ),
        migrations.AlterModelOptions(
            name="racunanjekompleksno",
            options={
                "verbose_name": "Kompleksna števila / računanje s kompleksno enoto"
            },
        ),
        migrations.AlterModelOptions(
            name="razstavirazliko",
            options={"verbose_name": "Razstavljanje / razlika potenc"},
        ),
        migrations.AlterModelOptions(
            name="razstavivieta",
            options={"verbose_name": "Razstavljanje / Vietovo pravilo"},
        ),
        migrations.AlterModelOptions(
            name="vsotakompleksnih",
            options={
                "verbose_name": "Kompleksna števila / seštevanje in odštevanje ulomkov"
            },
        ),
    ]
