# Generated by Django 3.2.6 on 2021-09-24 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0014_auto_20210924_1902"),
    ]

    operations = [
        migrations.AddField(
            model_name="problem",
            name="number_of_subproblems",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="Če je izbrana več kot ena naloga, bodo navodila našteta v seznamu.",
                verbose_name="število podnalog",
            ),
        ),
        migrations.AlterField(
            model_name="prostobesedilo",
            name="navodilo",
            field=models.TextField(
                default="Poljubno besedilo…",
                help_text="Poljubno besedilo navodila.",
                verbose_name="navodilo",
            ),
        ),
        migrations.AlterField(
            model_name="prostobesedilo",
            name="resitev",
            field=models.TextField(
                default="Poljubno besedilo…",
                help_text="Poljubno besedilo rešitve.",
                verbose_name="rešitev",
            ),
        ),
    ]
