# Generated by Django 4.1.3 on 2022-11-21 10:08

from django.db import migrations, models
import django.db.models.deletion
import problems.models.meta


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0008_alter_document_sort_alter_template_type"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("problems", "0015_auto_20210924_1903"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problem",
            name="content_type",
            field=models.ForeignKey(
                limit_choices_to=problems.models.meta.limit_content_type_choices,
                on_delete=django.db.models.deletion.PROTECT,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="problem",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="documents.document"
            ),
        ),
        migrations.AlterField(
            model_name="problem",
            name="text",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="problems.problemtext"
            ),
        ),
    ]
