# Generated by Django 4.1.3 on 2022-11-21 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0016_alter_problem_content_type_alter_problem_document_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problem",
            name="text",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="problems.problemtext",
            ),
        ),
    ]
