# Generated by Django 4.1.3 on 2022-11-29 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0017_alter_problem_text"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="problem",
            name="text",
        ),
        migrations.AddField(
            model_name="problem",
            name="instruction",
            field=models.TextField(blank=True, verbose_name="navodilo"),
        ),
        migrations.AddField(
            model_name="problem",
            name="solution",
            field=models.TextField(blank=True, verbose_name="rešitev"),
        ),
        migrations.DeleteModel(
            name="ProblemText",
        ),
    ]
