# Generated by Django 3.2.16 on 2022-11-24 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0017_alter_problem_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='SplosniClenZaporedja',
            fields=[
                ('problem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='problems.problem')),
                ('zamik_alternirajoce', models.BooleanField(choices=[(True, 'Da'), (False, 'Ne')], default=False, help_text='Določa, če so v izbor predpisa vljučena zamaknjena zaporedja iz kvadratov in  kubov ter alternirajoča zaporedja.', verbose_name='zamaknjeno in alternirajoče zaporedje')),
            ],
            options={
                'verbose_name': 'Zaporedja / splošni člen zaporedja',
            },
            bases=('problems.problem',),
        ),
    ]
