# Generated by Django 3.2.16 on 2022-12-01 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0018_splosniclenzaporedja'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrviCleniAritmeticnega',
            fields=[
                ('problem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='problems.problem')),
                ('racionalne_vrednosti', models.BooleanField(choices=[(True, 'Da'), (False, 'Ne')], default=False, verbose_name='prvi člen in diferenca zaporedja sta lahko racionalni vrednosti')),
            ],
            bases=('problems.problem',),
        ),
        migrations.AlterField(
            model_name='splosniclenzaporedja',
            name='zamik_alternirajoce',
            field=models.BooleanField(choices=[(True, 'Da'), (False, 'Ne')], default=False, help_text='So v izbor predpisa vljučena zamaknjena zaporedja iz kvadratov in  kubov ter alternirajoča zaporedja?', verbose_name='zamaknjeno in alternirajoče zaporedje'),
        ),
    ]
