# Generated by Django 4.1.3 on 2022-12-12 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0019_auto_20221201_1528"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="prvicleniaritmeticnega",
            options={"verbose_name": "Zaporedja / prvi člen aritmetičnega"},
        ),
        migrations.RemoveField(
            model_name="problem",
            name="text",
        ),
        migrations.AddField(
            model_name="problem",
            name="instruction",
            field=models.TextField(blank=True, verbose_name="navodilo"),
        ),
        migrations.AddField(
            model_name="problem",
            name="solution",
            field=models.TextField(blank=True, verbose_name="rešitev"),
        ),
        migrations.DeleteModel(
            name="ProblemText",
        ),
    ]
