# Generated by Django 3.2.16 on 2022-12-08 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0019_auto_20221201_1528"),
    ]

    operations = [
        migrations.CreateModel(
            name="GrafEksponentne",
            fields=[
                (
                    "problem_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="problems.problem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Eksponentna funkcija / risanje grafa",
            },
            bases=("problems.problem",),
        ),
        migrations.CreateModel(
            name="ResevanjeEksponentneEnacbe",
            fields=[
                (
                    "problem_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="problems.problem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Eksponentna funkcija / reševanje eksponentne enačbe z eno osnovo",
            },
            bases=("problems.problem",),
        ),
        migrations.CreateModel(
            name="ResevanjeEksponentneEnacbeZDvemaOsnovama",
            fields=[
                (
                    "problem_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="problems.problem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Eksponentna funkcija / reševanje eksponentne enačbe z različnima osnovama",
            },
            bases=("problems.problem",),
        ),
        migrations.AlterModelOptions(
            name="prvicleniaritmeticnega",
            options={"verbose_name": "Zaporedja / prvi člen aritmetičnega"},
        ),
    ]
