# Generated by Django 3.2.16 on 2022-12-12 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0020_auto_20221208_1829'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GrafEksponentne',
        ),
    ]
