# Generated by Django 3.2.16 on 2022-12-15 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0021_resevanjeeksponentneenacbe_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="IzracunNicelVPrimeruDvojneNicle",
            fields=[
                (
                    "problem_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="problems.problem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Polinomi / iskanje ničel v primeru dvojne ničle",
            },
            bases=("problems.problem",),
        ),
    ]
