# Generated by Django 3.2.16 on 2022-12-21 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0022_izracunnicelvprimerudvojnenicle"),
    ]

    operations = [
        migrations.CreateModel(
            name="KotMedGrafomaElementarnihFunkcij",
            fields=[
                (
                    "problem_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="problems.problem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Odvodi / računanje kota med elementarnimi funkcijami",
            },
            bases=("problems.problem",),
        ),
        migrations.CreateModel(
            name="KotMedPremicama",
            fields=[
                (
                    "problem_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="problems.problem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Odvodi / računanje kota med premicama",
            },
            bases=("problems.problem",),
        ),
        migrations.CreateModel(
            name="OdvodKompozitumaElementarnih",
            fields=[
                (
                    "problem_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="problems.problem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Odvodi / odvajanje kompozituma funkcij",
            },
            bases=("problems.problem",),
        ),
        migrations.CreateModel(
            name="OdvodSestavljene",
            fields=[
                (
                    "problem_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="problems.problem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Odvodi / odvajanje sestavljene funkcije",
            },
            bases=("problems.problem",),
        ),
        migrations.CreateModel(
            name="Tangenta",
            fields=[
                (
                    "problem_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="problems.problem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Odvodi / enačba tangente na graf v določeni točki",
            },
            bases=("problems.problem",),
        ),
    ]
