# Generated by Django 3.2.3 on 2021-08-19 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("students", "0002_auto_20210519_1621"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentgroup",
            name="user",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.PROTECT, to="users.user"
            ),
            preserve_default=False,
        ),
    ]
