# Generated by Django 3.2.6 on 2021-09-16 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_studentgroup_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="students",
                to="students.studentgroup",
                verbose_name="skupina",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="name",
            field=models.CharField(max_length=255, verbose_name="ime"),
        ),
        migrations.AlterField(
            model_name="studentgroup",
            name="name",
            field=models.CharField(max_length=255, verbose_name="ime"),
        ),
    ]
