# Generated by Django 3.2.6 on 2021-09-24 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0004_auto_20210916_0708"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentgroup",
            name="_students",
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name="Student",
        ),
    ]
