# Generated by Django 3.2.6 on 2021-09-16 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0004_auto_20210916_0708"),
        ("documents", "0002_alter_document_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Template",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="ime")),
                ("template", models.TextField(verbose_name="predloga")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("I", "posamezna datoteka za vsakega študenta"),
                            (
                                "S",
                                "združena datoteka za vse študente, urejena po študentih",
                            ),
                        ],
                        max_length=1,
                    ),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="document",
            options={"ordering": ["date", "name"]},
        ),
        migrations.AlterField(
            model_name="document",
            name="date",
            field=models.DateField(verbose_name="datum"),
        ),
        migrations.AlterField(
            model_name="document",
            name="description",
            field=models.TextField(blank=True, verbose_name="opis"),
        ),
        migrations.AlterField(
            model_name="document",
            name="name",
            field=models.CharField(max_length=255, verbose_name="ime"),
        ),
        migrations.AlterField(
            model_name="document",
            name="student_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="students.studentgroup",
                verbose_name="skupina",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="templates",
            field=models.ManyToManyField(
                to="documents.Template", verbose_name="predloge"
            ),
        ),
    ]
