# Generated by Django 3.2.6 on 2021-09-24 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0004_alter_document_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="document",
            old_name="description",
            new_name="introduction",
        ),
        migrations.AlterField(
            model_name="document",
            name="date",
            field=models.DateField(
                help_text="Datum, ki bo v glavi dokumenta in po katerem bodo urejeni dokumenti.",
                verbose_name="datum dokumenta",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="introduction",
            field=models.TextField(blank=True, verbose_name="uvodno besedilo"),
        ),
    ]
