# Generated by Django 3.2.6 on 2021-09-24 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0005_alter_document_introduction"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentSort",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="ime")),
                ("html_fragment", models.TextField()),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.RemoveField(
            model_name="document",
            name="templates",
        ),
        migrations.AddField(
            model_name="document",
            name="sort",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="documents.documentsort",
                verbose_name="vrsta",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="template",
            name="document_sort",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="documents.documentsort",
                verbose_name="vrsta dokumenta",
            ),
            preserve_default=False,
        ),
    ]
