# Generated by Django 3.2.6 on 2021-09-24 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0006_auto_20210924_0613"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documentsort",
            name="html_fragment",
        ),
    ]
