# Generated by Django 4.1.3 on 2022-11-21 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0007_remove_documentsort_html_fragment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="sort",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="documents.documentsort",
                verbose_name="oblika",
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="type",
            field=models.CharField(
                choices=[
                    ("I", "posamezna datoteka za vsakega učenca"),
                    ("S", "združena datoteka za vse učence, urejena po učencih"),
                    ("P", "združena datoteka za vse učence, urejena po nalogah"),
                ],
                max_length=1,
            ),
        ),
    ]
