# Generated by Django 4.1.3 on 2022-11-21 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0008_alter_document_sort_alter_template_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="date",
            field=models.DateField(
                help_text="Datum v glavi dokumenta in po katerem so urejeni dokumenti.",
                verbose_name="datum dokumenta",
            ),
        ),
    ]
