# Generated by Django 3.0.3 on 2020-02-13 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('testi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Naloga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generator', models.CharField(choices=[('UL', 'krajšanje ulomkov'), ('PO', 'iskanje ničel polinoma')], max_length=2)),
                ('zahtevnost', models.PositiveSmallIntegerField()),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='naloge', to='testi.Test')),
            ],
            options={
                'default_related_name': 'naloge',
            },
        ),
    ]
