# Generated by Django 3.0.3 on 2020-02-15 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('naloge', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='naloga',
            options={'default_related_name': 'naloge', 'verbose_name_plural': 'naloge'},
        ),
    ]
