# Generated by Django 3.0.7 on 2020-11-10 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("naslov", models.CharField(max_length=255)),
                ("datum", models.DateField()),
                ("opis", models.TextField(blank=True)),
            ],
            options={
                "verbose_name_plural": "testi",
                "ordering": ["datum", "naslov"],
            },
        ),
    ]
