# Generated by Django 3.0.3 on 2020-02-13 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naslov', models.CharField(max_length=255)),
                ('datum', models.DateField()),
                ('opis', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['datum', 'naslov'],
            },
        ),
    ]
